# Generated by Django 5.0.6 on 2024-06-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchboxmodel',
            name='lunchbox_summary',
            field=models.TextField(default='summary', help_text='Enter lunchbox summary', max_length=100),
        ),
    ]
